* Iffe * terms directive * correções CSS iOS * Animações

diff --git a/bin/upload b/bin/upload
--- a/bin/upload
+++ b/bin/upload
@@ -1,6 +1,17 @@
 #!/bin/bash
 # Usage: prod.sh 'platform'
 #
+
+# Abort if any command returns something else than 0
+set -e
+
+note="$1"
+
+if [[ -z "$1" ]]; then
+    echo "Not note, aborting..."
+    exit 1
+fi
+
 echo "Ionic Upload App"
 echo "Minify app"
 gulp prod
@@ -8,7 +19,7 @@ echo "Rename Folder to Minify Application"
 mv www temp
 mv dist www
 echo "Ionic Upload Start"
-ionic upload
+ionic upload --note "$note"
 echo "Rename folder"
 mv www dist
 mv temp www
